name: PROJECTNAME
recipe: wordpress
config:
  php: '8.3'
  via: nginx
  webroot: web
  database: 'mariadb:10.5'
  composer_version: 2
  xdebug: 'off'
  config:
    database: .lando/my.cnf
tooling:
  composer:
    description: Runs Composer commands
    cmd:
      - appserver: /usr/local/bin/composer
services:
  appserver:
    build_as_root:
      - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      - chmod +x wp-cli.phar
      - mv -f wp-cli.phar /usr/local/bin/wp
      - apt-get update && apt-get install -y jq
    run_as_root:
      - ln -snf /usr/share/zoneinfo/Europe/Helsinki /etc/localtime
      - echo "Europe/Helsinki" > /etc/timezone
      - ./create-wp-project.sh
  cache:
    type: 'redis:7'
    portforward: 6379
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
env_file:
  - .lando/.env
